[package]
name = "no_name"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "1.4"
hyper = "0.14"
matchit = "0.5"
tera = "1.15"
tls-listener = "0.5"
tokio = "1.17"
