-- Your SQL goes here
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions(
  sid VARCHAR(255) NOT NULL,
  data TEXT DEFAULT NULL,
  expiration BIGINT NOT NULL,
  PRIMARY KEY (sid)
);
CREATE EVENT IF NOT EXISTS auto_del ON SCHEDULE EVERY 1 HOUR ON COMPLETION PRESERVE DO
DELETE FROM
  sessions
WHERE
  expiration < UNIX_TIMESTAMP();